name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish_jvm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 10000
      # Fetch all tags so that sbt-dynver can find the previous release version
      - run: git fetch --tags -f
      # Install OpenJDK 21
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./sbt publish
